/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsChar123CategoryChar125RouteImport } from './routes/rooms.{-$category}'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsChar123CategoryChar125Route =
  RoomsChar123CategoryChar125RouteImport.update({
    id: '/rooms/{-$category}',
    path: '/rooms/{-$category}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/{-$category}': typeof RoomsChar123CategoryChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/{-$category}': typeof RoomsChar123CategoryChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/{-$category}': typeof RoomsChar123CategoryChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms/$slug' | '/rooms/{-$category}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms/$slug' | '/rooms/{-$category}'
  id: '__root__' | '/' | '/rooms/$slug' | '/rooms/{-$category}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsChar123CategoryChar125Route: typeof RoomsChar123CategoryChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/{-$category}': {
      id: '/rooms/{-$category}'
      path: '/rooms/{-$category}'
      fullPath: '/rooms/{-$category}'
      preLoaderRoute: typeof RoomsChar123CategoryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsChar123CategoryChar125Route: RoomsChar123CategoryChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
